

################ Get all ################ 

### comments

GET http://localhost:8080/api/comments


### posts
GET http://localhost:8080/api/posts

### User posts
GET http://localhost:8080/api/posts/451cb4ad-6307-4097-90db-a3b934e319d8

### reacts
GET http://localhost:8080/api/reacts

### reports
GET http://localhost:8080/api/reports


### saveForLaters
GET http://localhost:8080/api/saveForLaters

### User SaveForLaters Posts
GET http://localhost:8080/api/saveForLaters/935f2590-750e-48b0-b1a7-e68c538877f2

### users
GET http://localhost:8080/api/users

###############################################################

################ Create ################ 

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "type": 3 ,
  "text": "post 2",
  "attachments" : [],
  "isSaved": false,
  "isShared": false,
  "sharedPost":null ,
  "createdBy": {
    "id": "935f2590-750e-48b0-b1a7-e68c538877f2"
  },
  "moreData": [],
  "hashtags": []
}

###Users

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name" : "User 1",
  "picture" : "picture 1"
}


### Comment

POST http://localhost:8080/api/comments
Content-Type: application/json

{
  "post" : {
    "id": "a6e048b6-96d5-43ba-a921-d4ad59f7b9f9"
  },
  "parent" : null ,
  "text" : "Comment 1",
  "attachments" : [] ,
  "score" : 4 ,
  "createdBy":   {
    "id": "935f2590-750e-48b0-b1a7-e68c538877f2"
  },
  "createdAt": "2025-06-10T05:00:53.488657800" ,
  "updatedAt": "2025-06-10T05:00:53.488657800" 
}


### Save For Later

POST http://localhost:8080/api/saveForLaters
Content-Type: application/json

{
  "post" : {
    "id": "ca3ac564-4e0e-4214-8da6-24862cd0b505"
  },
  "createdBy":   {
    "id": "935f2590-750e-48b0-b1a7-e68c538877f2"
  },
  "createdAt": "2025-06-10T05:00:53.488657800" 
}


### React

POST http://localhost:8080/api/reacts
Content-Type: application/json

{
  "type" : 2 ,
  "post" : {
    "id": "d38a99d4-72d8-41c5-be87-8a391de83336"
  },
  "createdBy":   {
    "id": "f6f77fcd-70d6-4a49-b954-2d9b8dc6933e"
  }
}


###############################################################

################ Update ################ 


###React

Put http://localhost:8080/api/reacts/75fee2db-02ef-4901-8c46-7694e0535194
Content-Type: application/json

1


###Posts
Put http://localhost:8080/api/posts/238b29b2-9ccf-45de-86ce-118e2d191c25
Content-Type: application/json

{
  "type": 3 ,
  "text": "hii",
  "attachments" : [],
  "isSaved": false,
  "isShared": false,
  "sharedPost":null ,
  "createdBy": {
    "id": "55202e36-e379-44b7-9049-e261a38f8e61"
  },
  "createdAt": "2025-06-10T05:00:53.488657800" ,
  "updatedAt": "2025-06-10T05:00:53.488657800" ,
  "moreData": [],
  "hashtags": []
}

